import math

# === ROBOT PHYSICAL PARAMETERS ===
ROBOT_WIDTH = 0.24
ROBOT_LENGTH = 0.32
D_CENTER = ROBOT_LENGTH / 2.0

# === ROBOT OPERATIONAL LIMITS ===
MAX_LINEAR_SPEED = 0.1
MAX_ANGULAR_SPEED = math.radians(30)

# === STATE MACHINE BEHAVIORS ===
BACKUP_TIME = 1.5
BACKUP_SPEED = -0.08
APPROACH_SPEED = 0.08

# === FINAL APPROACH PARAMETERS ===
GRIPPER_DISTANCE = 0.32
FINAL_APPROACH_DISTANCE = 0.4
FINAL_DISTANCE_TOLERANCE = 0.01
FINAL_ANGLE_TOLERANCE = 0.02

# === P-CONTROLLER GAINS for FINAL_APPROACH ===
KP_LINEAR = 1.0
KP_ANGULAR = 1.0

# === QP CONTROLLER GAINS & PARAMETERS ===
QP_P_OMEGA = 1.0
QP_P_DELTA = 100.0
REF_K_V = 0.5
REF_K_OMEGA = 1.0
CLF_GAMMA = 1.0
CBF_ALPHA = 1.0
CBF_MARGIN = 0.01

# === VORTEX FIELD PARAMETERS ===
VORTEX_ACTIVATION_RADIUS = 0.6
VORTEX_FIELD_OF_VIEW_DEG = 180
VORTEX_STRENGTH_K = 150.0

# === LED COLOR ===
COLOR_RED = (255, 0, 0)
COLOR_YELLOW = (255, 255, 0)
COLOR_BLUE = (0, 0, 255)
COLOR_GREEN = (0, 255, 0)
COLOR_WHITE = (255, 255, 255)